var CityTxtDef = 'בחר יישוב';
var cities = [{ label: "א דהאבשה", value: "124" },
{ label: "א דיראת", value: "122" },
{ label: "א דנפירי", value: "205" },
{ label: "א זיאדנה דרומית לרהט", value: "179" },
{ label: "א זיאדנה צפונית לרהט", value: "179" },
{ label: "א זעיים", value: "96" },
{ label: "א טבקה", value: "122" },
{ label: "א טוואני", value: "122" },
{ label: "א לובאן", value: "92" },
{ label: "א נבארי", value: "199" },
{ label: "א נוואקיר", value: "141" },
{ label: "א סלבה", value: "59" },
{ label: "א ראם", value: "90" },
{ label: "א ראס", value: "165" },
{ label: "א ריחייה", value: "122" },
{ label: "א שהאדה", value: "158" },
{ label: "א שויוח", value: "85" },
{ label: "א שייח' אחמד", value: "171" },
{ label: "א.ת בראון", value: "165" },
{ label: "א.ת תנובות", value: "82" },
{ label: "אבו ג'אבר", value: "242" },
{ label: "אבו ג'ווייעד", value: "124" },
{ label: "אבו ג'ויעד", value: "124" },
{ label: "אבו גוש", value: "87" },
{ label: "אבו דיאב", value: "75" },
{ label: "אבו דיס", value: "96" },
{ label: "אבו טראש", value: "242" },
{ label: "אבו כף אום בטין", value: "242" },
{ label: "אבו נוג'ים", value: "95" },
{ label: "אבו סלמאן", value: "171" },
{ label: "אבו סנאן", value: "68" },
{ label: "אבו סריחאן", value: "242" },
{ label: "אבו עבדון", value: "242" },
{ label: "אבו עמאר", value: "242" },
{ label: "אבו עסא", value: "242" },
{ label: "אבו עפאש", value: "205" },
{ label: "אבו קוידר", value: "207" },
{ label: "אבו קורינאת", value: "124" },
{ label: "אבו קש", value: "90" },
{ label: "אבו רביעה", value: "124" },
{ label: "אבו רביעה צפונית לכסיפה", value: "124" },
{ label: "אבו ריקייק", value: "242" },
{ label: "אבו שחידם", value: "90" },
{ label: "אבו תלול", value: "207" },
{ label: "אבטין", value: "134" },
{ label: "אבטליון", value: "71" },
{ label: "אביאל", value: "181" },
{ label: "אביבים", value: "58" },
{ label: "אביגדור", value: "234" },
{ label: "אביחיל", value: "175" },
{ label: "אביטל", value: "236" },
{ label: "אביעזר", value: "99" },
{ label: "אבירים", value: "74" },
{ label: "אבן יהודה", value: "237" },
{ label: "אבן מנחם", value: "132" },
{ label: "אבן ספיר", value: "86" },
{ label: "אבן שמואל", value: "235" },
{ label: "אבני איתן", value: "46" },
{ label: "אבני חפץ", value: "165" },
{ label: "אבנת", value: "84" },
{ label: "אבשלום", value: "148" },
{ label: "אדורה", value: "122" },
{ label: "אדירים", value: "236" },
{ label: "אדמית", value: "141" },
{ label: "אדרת", value: "99" },
{ label: "אודים", value: "237" },
{ label: "אודלה", value: "165" },
{ label: "אודם", value: "44" },
{ label: "אוהד", value: "144" },
{ label: "אוהלו", value: "49" },
{ label: "אולפני נווה אילן", value: "87" },
{ label: "אום א טלע", value: "95" },
{ label: "אום א סח'אלי", value: "75" },
{ label: "אום א ריחאן", value: "156" },
{ label: "אום א תות", value: "158" },
{ label: "אום אל פחם", value: "180" },
{ label: "אום אל קוטוף", value: "187" },
{ label: "אום דאר", value: "156" },
{ label: "אום סלמונה", value: "95" },
{ label: "אום ספא", value: "88" },
{ label: "אום עלאס", value: "100" },
{ label: "אום עסלה", value: "95" },
{ label: "אומן", value: "236" },
{ label: "אומץ", value: "70" },
{ label: "אופקים", value: "43" },
{ label: "אור הגנוז", value: "52" },
{ label: "אור הנר", value: "188" },
{ label: "אור יהודה", value: "117" },
{ label: "אור עקיבא", value: "190" },
{ label: "אורה", value: "86" },
{ label: "אורון", value: "125" },
{ label: "אורות", value: "234" },
{ label: "אורטל", value: "222" },
{ label: "אורים", value: "195" },
{ label: "אורנים", value: "128" },
{ label: "אורנית", value: "115" },
{ label: "אושה", value: "134" },
{ label: "אזור", value: "104" },
{ label: "אזור תעסוקה מיתרים", value: "122" },
{ label: "אזור תעשיות צבאים", value: "154" },
{ label: "אזור תעשייה אכזיב מילואות", value: "143" },
{ label: "אזור תעשייה אלון התבור", value: "161" },
{ label: "אזור תעשייה אשקלון", value: "170" },
{ label: "אזור תעשייה בני יהודה", value: "46" },
{ label: "אזור תעשייה נ.ע.מ", value: "157" },
{ label: "אזור תעשייה נעמן", value: "220" },
{ label: "אזור תעשייה ספיר", value: "246" },
{ label: "אזור תעשייה רמת בקע", value: "205" },
{ label: "אזור תעשייה שגיא 2000", value: "126" },
{ label: "אזור תעשייה שער בנימין", value: "89" },
{ label: "אזור תעשייה תנובות", value: "82" },
{ label: "אחווה", value: "234" },
{ label: "אחוזם", value: "235" },
{ label: "אחוזת ברק", value: "161" },
{ label: "אחוזת שושנה", value: "154" },
{ label: "אחיהוד", value: "75" },
{ label: "אחיטוב", value: "70" },
{ label: "אחיסמך", value: "239" },
{ label: "אחיעזר", value: "238" },
{ label: "איבים", value: "198" },
{ label: "איג'ניסיניא", value: "158" },
{ label: "אידמית", value: "141" },
{ label: "אייל", value: "178" },
{ label: "איילת השחר", value: "54" },
{ label: "איכתאבא", value: "158" },
{ label: "אילון", value: "141" },
{ label: "אילות", value: "216" },
{ label: "אילנות", value: "178" },
{ label: "אילניה", value: "136" },
{ label: "אילת", value: "216" },
{ label: "אימאתין", value: "165" },
{ label: "אימריש", value: "122" },
{ label: "איסכאכא", value: "88" },
{ label: "אירוס", value: "109" },
{ label: "אירתאח", value: "158" },
{ label: "איתמר", value: "165" },
{ label: "איתן", value: "235" },
{ label: "איתנים", value: "87" },
{ label: "אכסאל", value: "81" },
{ label: "אל אסד", value: "242" },
{ label: "אל בירה", value: "90" },
{ label: "אל בירה בהר חברון", value: "204" },
{ label: "אל ג'ארושיה", value: "158" },
{ label: "אל ג'וויני", value: "124" },
{ label: "אל ג'נאמי", value: "124" },
{ label: "אל ג'רג'אווי", value: "205" },
{ label: "אל הג'רה", value: "122" },
{ label: "אל הייל", value: "179" },
{ label: "אל ולג'ה", value: "96" },
{ label: "אל ולידי", value: "205" },
{ label: "אל חדב", value: "122" },
{ label: "אל ח'דר", value: "95" },
{ label: "אל ח'וואלד מערב", value: "134" },
{ label: "אל חוקוק", value: "179" },
{ label: "אל חמידי", value: "207" },
{ label: "אל כלאב", value: "205" },
{ label: "אל מאג'ור", value: "122" },
{ label: "אל מודוור", value: "171" },
{ label: "אל מוטילה", value: "158" },
{ label: "אל מוע'ייר", value: "158" },
{ label: "אל מועלקה", value: "187" },
{ label: "אל מראג'ם", value: "122" },
{ label: "אל סייד", value: "199" },
{ label: "אל עביד", value: "124" },
{ label: "אל ע'ול", value: "125" },
{ label: "אל עזי", value: "234" },
{ label: "אל עטאונה", value: "199" },
{ label: "אל עלקה אל פוקא", value: "122" },
{ label: "אל עמראני", value: "125" },
{ label: "אל ערוב ", value: "85" },
{ label: "אל עריאן", value: "187" },
{ label: "אל עתאיקה", value: "179" },
{ label: "אל עת'אמין", value: "207" },
{ label: "אל פוואר", value: "122" },
{ label: "אל פונדוק", value: "165" },
{ label: "אל קוסור", value: "122" },
{ label: "אל קורעאן ב", value: "124" },
{ label: "אל קילא", value: "100" },
{ label: "אל קרישי", value: "124" },
{ label: "אל קרעאן", value: "124" },
{ label: "אל קשכר", value: "124" },
{ label: "אל רום", value: "44" },
{ label: "אלומה", value: "186" },
{ label: "אלומות", value: "49" },
{ label: "אלון", value: "93" },
{ label: "אלון הגליל", value: "75" },
{ label: "אלון מורה", value: "165" },
{ label: "אלון שבות", value: "85" },
{ label: "אלוני אבא", value: "126" },
{ label: "אלוני הבשן", value: "222" },
{ label: "אלוני יצחק", value: "181" },
{ label: "אלונים", value: "128" },
{ label: "אלי עד", value: "78" },
{ label: "אליכין", value: "78" },
{ label: "אליפז", value: "215" },
{ label: "אליפלט", value: "60" },
{ label: "אליקים", value: "173" },
{ label: "אלישיב", value: "78" },
{ label: "אלישמע", value: "115" },
{ label: "אלמגור", value: "60" },
{ label: "אלמוג", value: "93" },
{ label: "אלעד", value: "118" },
{ label: "אלעזר", value: "85" },
{ label: "אלפי מנשה", value: "171" },
{ label: "אלקוש", value: "74" },
{ label: "אלקנה", value: "171" },
{ label: "אמונים", value: "193" },
{ label: "אמירים", value: "52" },
{ label: "אמנון", value: "60" },
{ label: "אמציה", value: "204" },
{ label: "אניעם", value: "59" },
{ label: "אסדת תמר ומרי בי", value: "253" },
{ label: "אספר", value: "95" },
{ label: "אעבלין", value: "75" },
{ label: "אעצם", value: "199" },
{ label: "אפיניש", value: "122" },
{ label: "אפיק", value: "46" },
{ label: "אפיקים", value: "49" },
{ label: "אפק", value: "134" },
{ label: "אפרת", value: "85" },
{ label: "אקרע", value: "158" },
{ label: "ארבל", value: "53" },
{ label: "ארגמן", value: "163" },
{ label: "ארז", value: "188" },
{ label: "ארטאס", value: "95" },
{ label: "אריאל", value: "168" },
{ label: "ארסוף", value: "237" },
{ label: "אשבול", value: "160" },
{ label: "אשבל", value: "71" },
{ label: "אשדוד", value: "196" },
{ label: "אשדות יעקב איחוד", value: "49" },
{ label: "אשדות יעקב מאוחד", value: "49" },
{ label: "אשחר", value: "71" },
{ label: "אשכולות", value: "204" },
{ label: "אשל הנשיא בי''ס אזורי", value: "203" },
{ label: "אשלים", value: "223" },
{ label: "אשקלון", value: "172" },
{ label: "אשרת", value: "68" },
{ label: "אשתאול", value: "99" },
{ label: "אתגר", value: "75" },
{ label: "באקה", value: "165" },
{ label: "באקה א שרקיה", value: "158" },
{ label: "באקה אל ע'רביה", value: "70" },
{ label: "באקה ג'ת", value: "70" },
{ label: "באר אורה", value: "215" },
{ label: "באר גנים", value: "172" },
{ label: "באר טוביה", value: "234" },
{ label: "באר יעקב", value: "106" },
{ label: "באר מילכה", value: "210" },
{ label: "באר שבע", value: "209" },
{ label: "בארות יצחק", value: "118" },
{ label: "בארותיים", value: "82" },
{ label: "בארי", value: "135" },
{ label: "בד פלוח", value: "95" },
{ label: "בודרוס", value: "105" },
{ label: "בווידיעה", value: "95" },
{ label: "בוסתן הגליל", value: "69" },
{ label: "בוקעתא", value: "44" },
{ label: "בור אל מכסור", value: "75" },
{ label: "בורג'", value: "204" },
{ label: "בורגתה", value: "82" },
{ label: "בורהאם", value: "88" },
{ label: "בורוקין", value: "88" },
{ label: "בורין", value: "165" },
{ label: "בורקה", value: "90" },
{ label: "בורקה ליד שכם", value: "156" },
{ label: "בורקין", value: "156" },
{ label: "בזאריה", value: "158" },
{ label: "בחן", value: "70" },
{ label: "בטחה", value: "203" },
{ label: "ביאדה", value: "95" },
{ label: "בידו", value: "98" },
{ label: "בידיה", value: "171" },
{ label: "ביכורה", value: "154" },
{ label: "בילעין", value: "90" },
{ label: "בי''ס אזורי מקיף מטה אשר", value: "152" },
{ label: "ביצרון", value: "201" },
{ label: "ביר אבו אל חמאם", value: "207" },
{ label: "ביר הדאג'", value: "223" },
{ label: "ביר נבאלה", value: "96" },
{ label: "ביריה", value: "51" },
{ label: "בית א אל פוקא", value: "165" },
{ label: "בית א רוש אל פוקא", value: "204" },
{ label: "בית אולא", value: "100" },
{ label: "בית אומר", value: "85" },
{ label: "בית אומרין", value: "158" },
{ label: "בית אורן", value: "129" },
{ label: "בית איבא", value: "165" },
{ label: "בית איגיזא", value: "91" },
{ label: "בית איכסא", value: "96" },
{ label: "בית איענאן", value: "90" },
{ label: "בית אל", value: "90" },
{ label: "בית אלעזרי", value: "112" },
{ label: "בית אלפא", value: "154" },
{ label: "בית אמין", value: "171" },
{ label: "בית אריה", value: "92" },
{ label: "בית ברל", value: "178" },
{ label: "בית גוברין", value: "232" },
{ label: "בית ג'מאל", value: "99" },
{ label: "בית גמליאל", value: "113" },
{ label: "בית ג'ן", value: "64" },
{ label: "בית דגן", value: "238" },
{ label: "בית דג'ן", value: "165" },
{ label: "בית דוקו", value: "90" },
{ label: "בית הגדי", value: "157" },
{ label: "בית הלוי", value: "82" },
{ label: "בית הלל", value: "55" },
{ label: "בית העמק", value: "69" },
{ label: "בית השיטה", value: "154" },
{ label: "בית וזן", value: "165" },
{ label: "בית זיד", value: "128" },
{ label: "בית זית", value: "98" },
{ label: "בית זרע", value: "49" },
{ label: "בית חולים פורייה", value: "49" },
{ label: "בית חורון", value: "90" },
{ label: "בית חזון", value: "78" },
{ label: "בית חלקיה", value: "112" },
{ label: "בית חנינא", value: "96" },
{ label: "בית חנן", value: "241" },
{ label: "בית חנניה", value: "181" },
{ label: "בית חרות", value: "76" },
{ label: "בית חשמונאי", value: "108" },
{ label: "בית יהושע", value: "237" },
{ label: "בית יוסף", value: "154" },
{ label: "בית ינאי", value: "76" },
{ label: "בית יצחק שער חפר", value: "175" },
{ label: "בית ירח", value: "49" },
{ label: "בית כאחיל", value: "85" },
{ label: "בית לחם הגלילית", value: "126" },
{ label: "בית ליד", value: "165" },
{ label: "בית ליקיא", value: "90" },
{ label: "בית מאיר", value: "87" },
{ label: "בית מירסים", value: "204" },
{ label: "בית נחמיה", value: "103" },
{ label: "בית ניר", value: "232" },
{ label: "בית נקופה", value: "98" },
{ label: "בית סירא", value: "90" },
{ label: "בית סכריא", value: "85" },
{ label: "בית עובד", value: "241" },
{ label: "בית עוזיאל", value: "108" },
{ label: "בית עזרא", value: "193" },
{ label: "בית עיור א תחתא", value: "90" },
{ label: "בית עיור אל פוקא", value: "90" },
{ label: "בית עינון", value: "122" },
{ label: "בית עמרה", value: "122" },
{ label: "בית עריף", value: "103" },
{ label: "בית פוריכ", value: "165" },
{ label: "בית צבי", value: "130" },
{ label: "בית קאד", value: "158" },
{ label: "בית קמה", value: "179" },
{ label: "בית קשת", value: "136" },
{ label: "בית רבן", value: "113" },
{ label: "בית רחאל", value: "95" },
{ label: "בית רימא", value: "88" },
{ label: "בית רימון", value: "72" },
{ label: "בית שאן", value: "154" },
{ label: "בית שמש", value: "99" },
{ label: "בית שערים", value: "126" },
{ label: "בית שקמה", value: "169" },
{ label: "בית תעמר", value: "95" },
{ label: "ביתא א תחתא", value: "165" },
{ label: "ביתוניא", value: "90" },
{ label: "ביתילו", value: "90" },
{ label: "ביתין", value: "90" },
{ label: "ביתן אהרן", value: "175" },
{ label: "ביתר עילית", value: "85" },
{ label: "בלאטה", value: "165" },
{ label: "בלעא", value: "158" },
{ label: "בלפוריה", value: "81" },
{ label: "בן זכאי", value: "113" },
{ label: "בן עמי", value: "152" },
{ label: "בן שמן", value: "239" },
{ label: "בן שמן כפר נוער", value: "239" },
{ label: "בני ברק", value: "120" },
{ label: "בני דקלים", value: "204" },
{ label: "בני דרום", value: "196" },
{ label: "בני דרור", value: "178" },
{ label: "בני יהודה", value: "46" },
{ label: "בני נעים", value: "122" },
{ label: "בני נצרים", value: "150" },
{ label: "בני עטרות", value: "118" },
{ label: "בני עי''ש", value: "201" },
{ label: "בני ציון", value: "237" },
{ label: "בני ראם", value: "112" },
{ label: "בניה", value: "113" },
{ label: "בנימינה גבעת עדה", value: "181" },
{ label: "בסמ''ה", value: "180" },
{ label: "בסמת טבעון", value: "128" },
{ label: "בענה", value: "66" },
{ label: "בצרה", value: "237" },
{ label: "בצת", value: "143" },
{ label: "בקוע", value: "99" },
{ label: "בקעות", value: "163" },
{ label: "בר גיורא", value: "87" },
{ label: "בר יוחאי", value: "52" },
{ label: "ברדלה", value: "163" },
{ label: "ברוכים קלע אלון", value: "59" },
{ label: "ברוכין", value: "92" },
{ label: "ברור חיל", value: "164" },
{ label: "ברורים", value: "112" },
{ label: "ברוש", value: "159" },
{ label: "ברכה", value: "165" },
{ label: "ברכיה", value: "191" },
{ label: "ברעם", value: "58" },
{ label: "ברק", value: "236" },
{ label: "ברקאי", value: "187" },
{ label: "ברקן", value: "168" },
{ label: "ברקת", value: "103" },
{ label: "בת הדר", value: "169" },
{ label: "בת חן", value: "70" },
{ label: "בת חפר", value: "82" },
{ label: "בת ים", value: "104" },
{ label: "בת עין", value: "85" },
{ label: "בת שלמה", value: "185" },
{ label: "בתי זיקוק חיפה", value: "79" },
{ label: "בתיר ", value: "85" },
{ label: "גאולי תימן", value: "76" },
{ label: "גאולים", value: "178" },
{ label: "ג'אלוד", value: "89" },
{ label: "גאליה", value: "110" },
{ label: "ג'אניה", value: "90" },
{ label: "גבולות", value: "194" },
{ label: "גבים", value: "198" },
{ label: "גבע", value: "236" },
{ label: "ג'בע", value: "158" },
{ label: "גבע בנימין/אדם", value: "93" },
{ label: "גבע כרמל", value: "130" },
{ label: "גבעולים", value: "159" },
{ label: "גבעון החדשה", value: "91" },
{ label: "גבעות בר", value: "179" },
{ label: "גבעות עדן", value: "99" },
{ label: "גבעת  שמש", value: "99" },
{ label: "גבעת אבני", value: "49" },
{ label: "גבעת אולגה", value: "189" },
{ label: "גבעת אלה", value: "126" },
{ label: "גבעת אסף", value: "90" },
{ label: "גבעת ברנר", value: "109" },
{ label: "גבעת השלושה", value: "119" },
{ label: "גבעת וולפסון", value: "129" },
{ label: "גבעת זאב", value: "91" },
{ label: "גבעת חביבה", value: "183" },
{ label: "גבעת חיים איחוד", value: "78" },
{ label: "גבעת חיים מאוחד", value: "78" },
{ label: "גבעת ח''ן", value: "114" },
{ label: "גבעת יואב", value: "46" },
{ label: "גבעת יערים", value: "87" },
{ label: "גבעת ישעיהו", value: "101" },
{ label: "גבעת כ''ח", value: "118" },
{ label: "גבעת ניל''י", value: "181" },
{ label: "גבעת סנה יעקב", value: "165" },
{ label: "גבעת עוז", value: "180" },
{ label: "גבעת שמואל", value: "120" },
{ label: "גבעת שמש", value: "99" },
{ label: "גבעת שפירא", value: "175" },
{ label: "גבעתי", value: "193" },
{ label: "גבעתיים", value: "120" },
{ label: "גברעם", value: "166" },
{ label: "גבת", value: "126" },
{ label: "גדות", value: "54" },
{ label: "ג'דידה מכר", value: "69" },
{ label: "גדיש", value: "236" },
{ label: "גדעונה", value: "236" },
{ label: "גדרה", value: "112" },
{ label: "ג'האלין", value: "97" },
{ label: "ג'וב א רום", value: "95" },
{ label: "ג'ודידה", value: "158" },
{ label: "ג'והזם", value: "95" },
{ label: "ג'וליס", value: "68" },
{ label: "ג'וניד", value: "165" },
{ label: "גונן", value: "56" },
{ label: "ג'ועארה", value: "173" },
{ label: "ג'ורדיח", value: "141" },
{ label: "ג'וריש", value: "89" },
{ label: "גורן", value: "141" },
{ label: "גורנות הגליל", value: "141" },
{ label: "גזית", value: "136" },
{ label: "גזר", value: "108" },
{ label: "גיאה", value: "226" },
{ label: "גיב", value: "91" },
{ label: "גיבע מצפון לירושלים ", value: "90" },
{ label: "גיבתון", value: "109" },
{ label: "גיודירה", value: "91" },
{ label: "ג'יוס", value: "165" },
{ label: "גיזו", value: "99" },
{ label: "גילון", value: "66" },
{ label: "גילזון", value: "90" },
{ label: "גילת", value: "203" },
{ label: "גימאלא", value: "90" },
{ label: "גינוסר", value: "53" },
{ label: "גיניגר", value: "126" },
{ label: "ג'ינסאפוט", value: "171" },
{ label: "גינתון", value: "239" },
{ label: "גיפנא", value: "90" },
{ label: "ג'ית", value: "165" },
{ label: "גיתה", value: "68" },
{ label: "גיתית", value: "167" },
{ label: "גלאון", value: "202" },
{ label: "ג'לבון", value: "158" },
{ label: "ג'לג'וליה", value: "115" },
{ label: "גלגל", value: "83" },
{ label: "גליל ים", value: "116" },
{ label: "ג'למה", value: "158" },
{ label: "גלעד (אבן יצחק)", value: "173" },
{ label: "ג'מאעין", value: "165" },
{ label: "גמזו", value: "105" },
{ label: "גן הדרום", value: "233" },
{ label: "גן השומרון", value: "189" },
{ label: "גן התעשייה תל חי", value: "55" },
{ label: "גן חיים", value: "102" },
{ label: "גן יאשיה", value: "82" },
{ label: "גן יבנה", value: "233" },
{ label: "גן נר", value: "236" },
{ label: "גן שורק", value: "107" },
{ label: "גן שלמה", value: "109" },
{ label: "גן שמואל", value: "183" },
{ label: "ג'נאביב", value: "124" },
{ label: "גנות", value: "238" },
{ label: "גנות הדר", value: "175" },
{ label: "גני הדר", value: "108" },
{ label: "גני טל", value: "112" },
{ label: "גני יוחנן", value: "108" },
{ label: "גני עם", value: "115" },
{ label: "גני תקווה", value: "117" },
{ label: "ג'נין", value: "158" },
{ label: "ג'סר א זרקא", value: "181" },
{ label: "געש", value: "237" },
{ label: "געתון", value: "151" },
{ label: "גפן", value: "101" },
{ label: "ג'רבה", value: "158" },
{ label: "ג'רון א לוז", value: "122" },
{ label: "גרופית", value: "215" },
{ label: "גשור", value: "46" },
{ label: "גשר", value: "154" },
{ label: "גשר הזיו", value: "62" },
{ label: "גת", value: "182" },
{ label: "ג'ת", value: "70" },
{ label: "גת רימון", value: "119" },
{ label: "דאלית אל כרמל", value: "129" },
{ label: "דאר אל חנון", value: "187" },
{ label: "דבורה", value: "236" },
{ label: "דבוריה", value: "136" },
{ label: "דבירה", value: "179" },
{ label: "דברת", value: "161" },
{ label: "דגניה א", value: "49" },
{ label: "דגניה ב'", value: "49" },
{ label: "דהיישה מחנה פליטים", value: "95" },
{ label: "ד'הר אל עבד", value: "187" },
{ label: "ד'הר חלת אל ג'אמיע", value: "95" },
{ label: "דהרייה", value: "122" },
{ label: "דוב''ב", value: "245" },
{ label: "דולב", value: "90" },
{ label: "דומא ", value: "83" },
{ label: "דור", value: "185" },
{ label: "דורא", value: "85" },
{ label: "דורא אל קריע", value: "90" },
{ label: "דורות", value: "228" },
{ label: "דחי", value: "161" },
{ label: "דייר חנא", value: "71" },
{ label: "דייר ראפאת", value: "99" },
{ label: "דימונה", value: "125" },
{ label: "דיר אבו דעיף", value: "158" },
{ label: "דיר איבזיע", value: "90" },
{ label: "דיר איסתיא", value: "171" },
{ label: "דיר אל אסד", value: "66" },
{ label: "דיר אל חטב", value: "165" },
{ label: "דיר אל משעל", value: "88" },
{ label: "דיר אל סודאן ", value: "88" },
{ label: "דיר אל ע'וסוף", value: "158" },
{ label: "דיר בלוט", value: "92" },
{ label: "דיר ג'ריר", value: "89" },
{ label: "דיר דיבוואן ", value: "89" },
{ label: "דיר כרמיזן", value: "96" },
{ label: "דיר ניזאם", value: "88" },
{ label: "דיר סאמת", value: "122" },
{ label: "דיר ע'זאלה", value: "158" },
{ label: "דיר עמאר", value: "90" },
{ label: "דיר ע'סאנה", value: "88" },
{ label: "דיר ראזח", value: "122" },
{ label: "דיר שרף", value: "165" },
{ label: "דישון", value: "57" },
{ label: "דליה", value: "173" },
{ label: "דלתון", value: "61" },
{ label: "דמיידה", value: "75" },
{ label: "דן", value: "50" },
{ label: "דנאבה", value: "158" },
{ label: "דפנה", value: "50" },
{ label: "דקל", value: "148" },
{ label: "דריג'את", value: "124" },
{ label: "ה", value: "95" },
{ label: "האון", value: "48" },
{ label: "האשימיה", value: "156" },
{ label: "הבונים", value: "185" },
{ label: "הגושרים", value: "50" },
{ label: "הדר עם", value: "175" },
{ label: "הוד השרון", value: "115" },
{ label: "הודיה", value: "191" },
{ label: "הודיות ", value: "49" },
{ label: "הוואשלה", value: "125" },
{ label: "הוזייל", value: "179" },
{ label: "הושעיה", value: "81" },
{ label: "הזורע", value: "173" },
{ label: "הזורעים", value: "49" },
{ label: "החותרים", value: "80" },
{ label: "היוגב", value: "139" },
{ label: "הילה", value: "149" },
{ label: "הכפר הירוק", value: "116" },
{ label: "המעפיל", value: "70" },
{ label: "הסוללים", value: "81" },
{ label: "העוגן", value: "82" },
{ label: "הר אדר", value: "98" },
{ label: "הר גילה", value: "85" },
{ label: "הר גריזים", value: "165" },
{ label: "הר עמשא", value: "122" },
{ label: "הראל", value: "99" },
{ label: "הרדוף", value: "75" },
{ label: "הרצליה", value: "116" },
{ label: "הררית", value: "71" },
{ label: "ואדי א דבע", value: "158" },
{ label: "ואדי חמאם", value: "53" },
{ label: "ואדי על עראיסה", value: "95" },
{ label: "ואדי פוכין", value: "85" },
{ label: "ואדיח", value: "122" },
{ label: "ורד הגליל", value: "60" },
{ label: "ורד יריחו", value: "93" },
{ label: "ורדון", value: "186" },
{ label: "ורדים מוסד חינוכי", value: "237" },
{ label: "זאוויה בצפון שומרון", value: "158" },
{ label: "זבאבידה", value: "158" },
{ label: "זבארגה", value: "124" },
{ label: "זבדיאל", value: "186" },
{ label: "זובובא", value: "156" },
{ label: "זובידאת", value: "163" },
{ label: "זוהר", value: "184" },
{ label: "זוואתא", value: "165" },
{ label: "זיבדה", value: "156" },
{ label: "זיף", value: "122" },
{ label: "זיקים", value: "131" },
{ label: "זיתא", value: "165" },
{ label: "זיתא ליד באקה אל ע'רביה", value: "70" },
{ label: "זיתן", value: "238" },
{ label: "זכרון יעקב", value: "185" },
{ label: "זכריה", value: "101" },
{ label: "זמר", value: "70" },
{ label: "זמרת", value: "133" },
{ label: "זנוח", value: "99" },
{ label: "זעתרה", value: "95" },
{ label: "זרועה", value: "229" },
{ label: "זרזיר", value: "126" },
{ label: "זרחיה", value: "186" },
{ label: "זרעית", value: "132" },
{ label: "חארס", value: "168" },
{ label: "חבלה", value: "115" },
{ label: "חבצלת השרון", value: "175" },
{ label: "חבר", value: "236" },
{ label: "חברון", value: "122" },
{ label: "חג'ה", value: "165" },
{ label: "חגור", value: "115" },
{ label: "חגי", value: "122" },
{ label: "חגלה", value: "78" },
{ label: "חד נס", value: "59" },
{ label: "חדיד", value: "103" },
{ label: "חדרה", value: "221" },
{ label: "ח'ואלד", value: "75" },
{ label: "חוג'ייראת ד'הרה", value: "71" },
{ label: "חוג'ילה", value: "95" },
{ label: "ח'ווארה", value: "165" },
{ label: "חוות גלעד", value: "165" },
{ label: "חוות דושן", value: "154" },
{ label: "חוות יזרעם", value: "133" },
{ label: "חוות עדן", value: "154" },
{ label: "חוות שיקמים", value: "162" },
{ label: "חוות שלם", value: "120" },
{ label: "חוות שפעה", value: "154" },
{ label: "חולדה", value: "108" },
{ label: "חולון", value: "104" },
{ label: "חולית", value: "176" },
{ label: "חולתה", value: "54" },
{ label: "חוסן", value: "149" },
{ label: "חוסנייה", value: "71" },
{ label: "חופית", value: "76" },
{ label: "חוקוק", value: "53" },
{ label: "חורה", value: "199" },
{ label: "חורפיש", value: "145" },
{ label: "חורשים", value: "115" },
{ label: "חזון", value: "71" },
{ label: "חיבת ציון", value: "78" },
{ label: "חיזמא", value: "96" },
{ label: "חיננית", value: "156" },
{ label: "חיפה", value: "80" },
{ label: "ח'ירבת א טורם", value: "156" },
{ label: "ח'ירבת א טייבה", value: "156" },
{ label: "ח'ירבת א טירה", value: "90" },
{ label: "ח'ירבת א נבי אליאס", value: "171" },
{ label: "ח'ירבת אבו פלאח", value: "89" },
{ label: "ח'ירבת אל אשקר", value: "171" },
{ label: "ח'ירבת אל מיסבאח", value: "90" },
{ label: "ח'ירבת אל עכאבה", value: "187" },
{ label: "ח'ירבת אל עקרבאניה", value: "158" },
{ label: "ח'ירבת בית חסן", value: "158" },
{ label: "ח'ירבת זיתא", value: "122" },
{ label: "ח'ירבת כרמה", value: "122" },
{ label: "ח'ירבת מועאוויה", value: "180" },
{ label: "ח'ירבת סיר", value: "165" },
{ label: "ח'ירבת עסלה", value: "171" },
{ label: "ח'ירבת קיס", value: "88" },
{ label: "ח'ירבת ראס א טירה", value: "171" },
{ label: "ח'ירבת ראס עטיה", value: "171" },
{ label: "ח'ירבתא", value: "90" },
{ label: "חלוץ", value: "64" },
{ label: "חלחול", value: "85" },
{ label: "חלמיש", value: "88" },
{ label: "חלץ", value: "164" },
{ label: "ח'לת אל פולה", value: "163" },
{ label: "חמד", value: "238" },
{ label: "חמדיה", value: "154" },
{ label: "חמדת", value: "163" },
{ label: "חמדת ימים", value: "52" },
{ label: "חמרה", value: "163" },
{ label: "חמת גדר", value: "46" },
{ label: "חניאל", value: "82" },
{ label: "חניתה", value: "141" },
{ label: "חנתון", value: "75" },
{ label: "חסכה", value: "85" },
{ label: "חספין", value: "46" },
{ label: "חפץ חיים", value: "112" },
{ label: "חפצי בה", value: "154" },
{ label: "חצב", value: "201" },
{ label: "חצבה", value: "215" },
{ label: "חצור אשדוד", value: "233" },
{ label: "חצור הגלילית", value: "60" },
{ label: "חצרים", value: "208" },
{ label: "ח'ראס", value: "100" },
{ label: "חרב לאת", value: "78" },
{ label: "חרוצים", value: "237" },
{ label: "חרות", value: "178" },
{ label: "ח'רזאן", value: "95" },
{ label: "חרמלה", value: "95" },
{ label: "חרמש", value: "156" },
{ label: "ח'רסה", value: "122" },
{ label: "חרשים", value: "64" },
{ label: "ח'שם אל כרם", value: "122" },
{ label: "חשמונאים", value: "105" },
{ label: "טבריה", value: "45" },
{ label: "טובא זנגריה", value: "60" },
{ label: "טובאס", value: "158" },
{ label: "טול כרם", value: "158" },
{ label: "טורה על ע'רביה", value: "156" },
{ label: "טורעאן", value: "136" },
{ label: "טייבה", value: "178" },
{ label: "טייבה ליד מולדת", value: "236" },
{ label: "טירה", value: "178" },
{ label: "טירת יהודה", value: "103" },
{ label: "טירת כרמל", value: "80" },
{ label: "טירת צבי", value: "154" },
{ label: "טל אל", value: "68" },
{ label: "טל שחר", value: "99" },
{ label: "טלוזה", value: "158" },
{ label: "טללים", value: "223" },
{ label: "טלמון", value: "90" },
{ label: "טמון", value: "158" },
{ label: "טמרה", value: "75" },
{ label: "טמרה יזרעאל", value: "161" },
{ label: "טנא עומרים", value: "122" },
{ label: "טפחות", value: "47" },
{ label: "יאמון", value: "156" },
{ label: "יאנוח ג'ת", value: "65" },
{ label: "יאנון", value: "165" },
{ label: "יאסוף", value: "88" },
{ label: "יאסיד", value: "158" },
{ label: "יבול", value: "148" },
{ label: "יבור", value: "75" },
{ label: "יבנה", value: "110" },
{ label: "יבניאל", value: "49" },
{ label: "יברוד", value: "90" },
{ label: "יגור", value: "134" },
{ label: "יגל", value: "238" },
{ label: "יד בנימין", value: "112" },
{ label: "יד השמונה", value: "87" },
{ label: "יד חנה", value: "82" },
{ label: "יד מרדכי", value: "155" },
{ label: "יד נתן", value: "184" },
{ label: "יד רמב''ם", value: "108" },
{ label: "ידידה", value: "87" },
{ label: "יהוד מונוסון", value: "117" },
{ label: "יהל", value: "215" },
{ label: "יובל", value: "55" },
{ label: "יובלים", value: "75" },
{ label: "יודפת", value: "75" },
{ label: "יונתן", value: "222" },
{ label: "יוקנעם", value: "173" },
{ label: "יוקנעם עילית", value: "173" },
{ label: "יושיביה", value: "260" },
{ label: "יזרעאל", value: "236" },
{ label: "יחד", value: "71" },
{ label: "יחיעם", value: "151" },
{ label: "יטא יוטה", value: "122" },
{ label: "יטבתה", value: "215" },
{ label: "ייט''ב", value: "83" },
{ label: "יכיני", value: "212" },
{ label: "ים המלח בתי מלון", value: "123" },
{ label: "ימין אורד", value: "130" },
{ label: "ינוב", value: "82" },
{ label: "ינון", value: "197" },
{ label: "יסוד המעלה", value: "54" },
{ label: "יסודות", value: "108" },
{ label: "יסעור", value: "75" },
{ label: "יעבד", value: "156" },
{ label: "יעד", value: "75" },
{ label: "יעל", value: "236" },
{ label: "יעף", value: "178" },
{ label: "יערה", value: "141" },
{ label: "יפיע/יאפא", value: "81" },
{ label: "יפית", value: "167" },
{ label: "יפעת", value: "126" },
{ label: "יפתח", value: "57" },
{ label: "יצהר", value: "165" },
{ label: "יציץ", value: "108" },
{ label: "יקום", value: "237" },
{ label: "יקיר", value: "171" },
{ label: "יראון", value: "58" },
{ label: "ירדנה", value: "154" },
{ label: "ירוחם", value: "125" },
{ label: "ירושלים", value: "96" },
{ label: "ירחיב", value: "115" },
{ label: "יריחו", value: "93" },
{ label: "ירכא", value: "68" },
{ label: "ירקונה", value: "115" },
{ label: "ישע", value: "146" },
{ label: "ישעי", value: "99" },
{ label: "ישרש", value: "106" },
{ label: "יתד", value: "148" },
{ label: "יתמא", value: "89" },
{ label: "כאבול", value: "75" },
{ label: "כאוכב אבו אל היגא", value: "75" },
{ label: "כברי", value: "152" },
{ label: "כדורי", value: "136" },
{ label: "כובר", value: "88" },
{ label: "כוויזבא", value: "85" },
{ label: "כוחלה", value: "124" },
{ label: "כוכב השחר", value: "93" },
{ label: "כוכב יאיר", value: "178" },
{ label: "כוכב יעקב", value: "90" },
{ label: "כוכב מיכאל", value: "184" },
{ label: "כופיר", value: "158" },
{ label: "כופיראת", value: "156" },
{ label: "כור", value: "165" },
{ label: "כורזים", value: "60" },
{ label: "כחל", value: "53" },
{ label: "כימדע", value: "217" },
{ label: "כינרת מושבה", value: "49" },
{ label: "כינרת קבוצה", value: "49" },
{ label: "כיסופים", value: "138" },
{ label: "כיסרא סמיע", value: "65" },
{ label: "כיפל חארת", value: "168" },
{ label: "כישור", value: "67" },
{ label: "כליל", value: "68" },
{ label: "כלנית", value: "47" },
{ label: "כמאנה", value: "71" },
{ label: "כמאנה מזרח", value: "71" },
{ label: "כמהין", value: "210" },
{ label: "כמון", value: "71" },
{ label: "כנות", value: "201" },
{ label: "כנף", value: "59" },
{ label: "כנף 2", value: "219" },
{ label: "כסיפה", value: "124" },
{ label: "כסלון", value: "87" },
{ label: "כעאבנה", value: "122" },
{ label: "כעביה טבאש חג'אג'רה", value: "126" },
{ label: "כפר א דיכ", value: "88" },
{ label: "כפר א לבד", value: "158" },
{ label: "כפר אביב", value: "113" },
{ label: "כפר אדומים", value: "93" },
{ label: "כפר אוריה", value: "99" },
{ label: "כפר אזר", value: "117" },
{ label: "כפר אחים", value: "234" },
{ label: "כפר אלדד", value: "95" },
{ label: "כפר ביאליק", value: "220" },
{ label: "כפר ביל''ו", value: "108" },
{ label: "כפר בלום", value: "56" },
{ label: "כפר בן נון", value: "108" },
{ label: "כפר ברא", value: "115" },
{ label: "כפר ברוך", value: "139" },
{ label: "כפר גדעון", value: "81" },
{ label: "כפר גלים", value: "80" },
{ label: "כפר גליקסון", value: "181" },
{ label: "כפר גלעדי", value: "55" },
{ label: "כפר ג'מאל", value: "165" },
{ label: "כפר דאן", value: "156" },
{ label: "כפר דניאל", value: "109" },
{ label: "כפר הארנים", value: "105" },
{ label: "כפר החורש", value: "81" },
{ label: "כפר המכבי", value: "134" },
{ label: "כפר הנגיד", value: "110" },
{ label: "כפר הנוער הדתי", value: "134" },
{ label: "כפר הנשיא", value: "60" },
{ label: "כפר הס", value: "178" },
{ label: "כפר הרא''ה", value: "78" },
{ label: "כפר הרי''ף", value: "197" },
{ label: "כפר ויתקין", value: "76" },
{ label: "כפר ורבורג", value: "234" },
{ label: "כפר ורדים", value: "149" },
{ label: "כפר זוהרים", value: "101" },
{ label: "כפר זיבאד", value: "165" },
{ label: "כפר זיתים", value: "53" },
{ label: "כפר חב''ד", value: "238" },
{ label: "כפר חיטים", value: "53" },
{ label: "כפר חיים", value: "175" },
{ label: "כפר חנניה", value: "47" },
{ label: "כפר חסידים", value: "134" },
{ label: "כפר חסידים א'", value: "134" },
{ label: "כפר חרוב", value: "46" },
{ label: "כפר טרומן", value: "238" },
{ label: "כפר יאסיף", value: "68" },
{ label: "כפר ידידיה", value: "175" },
{ label: "כפר יהושע", value: "126" },
{ label: "כפר יונה", value: "82" },
{ label: "כפר יחזקאל", value: "236" },
{ label: "כפר יעבץ", value: "178" },
{ label: "כפר כמא", value: "49" },
{ label: "כפר כנא", value: "81" },
{ label: "כפר לאקף", value: "171" },
{ label: "כפר מאליכ", value: "89" },
{ label: "כפר מונש", value: "82" },
{ label: "כפר מימון", value: "133" },
{ label: "כפר מיסר", value: "136" },
{ label: "כפר מל''ל", value: "115" },
{ label: "כפר מנדא", value: "75" },
{ label: "כפר מנחם", value: "197" },
{ label: "כפר מסריק", value: "69" },
{ label: "כפר מרדכי", value: "113" },
{ label: "כפר נהר הירדן", value: "49" },
{ label: "כפר נוער עדנים", value: "179" },
{ label: "כפר נחום", value: "60" },
{ label: "כפר נטר", value: "237" },
{ label: "כפר ניעמה", value: "90" },
{ label: "כפר סאלד", value: "56" },
{ label: "כפר סבא", value: "102" },
{ label: "כפר סור", value: "165" },
{ label: "כפר סילבר", value: "191" },
{ label: "כפר סירקין", value: "119" },
{ label: "כפר עבודה", value: "178" },
{ label: "כפר עבוש", value: "165" },
{ label: "כפר עזה", value: "213" },
{ label: "כפר עין", value: "88" },
{ label: "כפר עציון", value: "85" },
{ label: "כפר עקב", value: "90" },
{ label: "כפר פינס", value: "189" },
{ label: "כפר קאסם", value: "115" },
{ label: "כפר קדום", value: "165" },
{ label: "כפר קוד", value: "156" },
{ label: "כפר קיש", value: "136" },
{ label: "כפר קליל", value: "165" },
{ label: "כפר קרע", value: "187" },
{ label: "כפר ראעי", value: "158" },
{ label: "כפר ראש הנקרה", value: "143" },
{ label: "כפר רומאן", value: "158" },
{ label: "כפר רופין", value: "154" },
{ label: "כפר רות", value: "105" },
{ label: "כפר שמאי", value: "52" },
{ label: "כפר שמואל", value: "108" },
{ label: "כפר שמריהו", value: "116" },
{ label: "כפר תבור", value: "136" },
{ label: "כפר ת'ולת", value: "171" },
{ label: "כפר תפוח", value: "88" },
{ label: "כפר תקווה", value: "128" },
{ label: "כרזה", value: "122" },
{ label: "כרי דשא", value: "60" },
{ label: "כרכום", value: "60" },
{ label: "כרם בן זמרה", value: "61" },
{ label: "כרם בן שמן", value: "239" },
{ label: "כרם יבנה", value: "113" },
{ label: "כרם מהר''ל", value: "185" },
{ label: "כרם עמי", value: "204" },
{ label: "כרם שלום", value: "153" },
{ label: "כרמי יוסף", value: "108" },
{ label: "כרמי צור", value: "85" },
{ label: "כרמי קטיף", value: "204" },
{ label: "כרמיאל", value: "66" },
{ label: "כרמיה", value: "131" },
{ label: "כרמיל", value: "122" },
{ label: "כרמים", value: "199" },
{ label: "כרמית", value: "199" },
{ label: "כשדה", value: "158" },
{ label: "לב יתיר", value: "122" },
{ label: "לבון", value: "66" },
{ label: "לביא", value: "49" },
{ label: "לבנים", value: "53" },
{ label: "להב", value: "230" },
{ label: "להבות הבשן", value: "56" },
{ label: "להבות חביבה", value: "70" },
{ label: "להבים", value: "179" },
{ label: "לובאן שרקיה", value: "88" },
{ label: "לוד", value: "239" },
{ label: "לוזית", value: "101" },
{ label: "לוחמי הגיטאות", value: "63" },
{ label: "לוטם", value: "71" },
{ label: "לוטן", value: "215" },
{ label: "לימן", value: "143" },
{ label: "לכיש", value: "202" },
{ label: "לפיד", value: "105" },
{ label: "לפידות", value: "68" },
{ label: "לקיה", value: "242" },
{ label: "מאור", value: "183" },
{ label: "מאיר שפיה", value: "185" },
{ label: "מבוא ביתר", value: "86" },
{ label: "מבוא דותן", value: "156" },
{ label: "מבוא חורון", value: "105" },
{ label: "מבוא חמה", value: "46" },
{ label: "מבוא מודיעים", value: "105" },
{ label: "מבואות ים", value: "76" },
{ label: "מבואות יריחו", value: "93" },
{ label: "מבועים", value: "160" },
{ label: "מבחור", value: "182" },
{ label: "מבטחים", value: "146" },
{ label: "מבקיעים", value: "226" },
{ label: "מבשרת ציון", value: "98" },
{ label: "מג'ד", value: "122" },
{ label: "מגדים", value: "130" },
{ label: "מגדל", value: "53" },
{ label: "מג'דל", value: "165" },
{ label: "מגדל העמק", value: "126" },
{ label: "מג'דל כרום", value: "66" },
{ label: "מגדל עוז", value: "85" },
{ label: "מג'דל שמס", value: "44" },
{ label: "מגדל תפן", value: "65" },
{ label: "מגדלים", value: "89" },
{ label: "מגידו", value: "173" },
{ label: "מגל", value: "70" },
{ label: "מגן", value: "174" },
{ label: "מגן שאול", value: "236" },
{ label: "מגשימים", value: "118" },
{ label: "מדמא", value: "165" },
{ label: "מדרך עוז", value: "173" },
{ label: "מדרשת בן גוריון", value: "127" },
{ label: "מודיעין מכבים רעות", value: "105" },
{ label: "מודיעין עילית", value: "105" },
{ label: "מוח'יים פארעה", value: "158" },
{ label: "מוח'מאס", value: "89" },
{ label: "מולדה", value: "199" },
{ label: "מולדת", value: "154" },
{ label: "מוע'ייר", value: "83" },
{ label: "מועסכר אל ערובה", value: "85" },
{ label: "מועצה אזורית אשכול", value: "174" },
{ label: "מועצה אזורית לב השרון", value: "178" },
{ label: "מוצא עילית", value: "98" },
{ label: "מוקייבלה", value: "236" },
{ label: "מורן", value: "71" },
{ label: "מורשת", value: "75" },
{ label: "מזור", value: "118" },
{ label: "מזכרת בתיה", value: "108" },
{ label: "מזרע", value: "81" },
{ label: "מזרעה", value: "63" },
{ label: "מזרעה א שרקיה", value: "89" },
{ label: "מזרעה אל קיבליה", value: "90" },
{ label: "מחולה", value: "163" },
{ label: "מחנה נחשונים", value: "218" },
{ label: "מחניים", value: "60" },
{ label: "מחסיה", value: "99" },
{ label: "מטולה", value: "55" },
{ label: "מטע", value: "87" },
{ label: "מי עמי", value: "180" },
{ label: "מידיה", value: "105" },
{ label: "מיטב", value: "236" },
{ label: "מייסר", value: "70" },
{ label: "מיכרות תמנע", value: "215" },
{ label: "מיניה", value: "95" },
{ label: "מיצר", value: "46" },
{ label: "מירב", value: "154" },
{ label: "מירון", value: "52" },
{ label: "מירכה", value: "158" },
{ label: "מישר", value: "113" },
{ label: "מית'לון", value: "158" },
{ label: "מיתר", value: "199" },
{ label: "מכון וינגייט", value: "237" },
{ label: "מכורה", value: "163" },
{ label: "מכחול", value: "124" },
{ label: "מכללת ספיר", value: "198" },
{ label: "מכמורת", value: "76" },
{ label: "מכמנים", value: "71" },
{ label: "מלאה", value: "236" },
{ label: "מלילות", value: "159" },
{ label: "מלכיה", value: "57" },
{ label: "מלכישוע", value: "154" },
{ label: "מנוחה", value: "186" },
{ label: "מנוף", value: "75" },
{ label: "מנות", value: "151" },
{ label: "מנזר לטרון", value: "99" },
{ label: "מנחמיה", value: "49" },
{ label: "מנסורה", value: "187" },
{ label: "מנרה", value: "55" },
{ label: "מנשה זבדה", value: "126" },
{ label: "מנשיה", value: "156" },
{ label: "מסד", value: "47" },
{ label: "מסדה", value: "48" },
{ label: "מסחה", value: "171" },
{ label: "מסילות", value: "154" },
{ label: "מסיליה", value: "158" },
{ label: "מסילת ציון", value: "99" },
{ label: "מסלול", value: "231" },
{ label: "מסעדה", value: "44" },
{ label: "מסעודין אל עזאזמה", value: "209" },
{ label: "מע'אר/מגאר", value: "47" },
{ label: "מעברות", value: "175" },
{ label: "מעגלים", value: "159" },
{ label: "מעגן", value: "48" },
{ label: "מעגן מיכאל", value: "181" },
{ label: "מעוז חיים", value: "154" },
{ label: "מעון", value: "122" },
{ label: "מעונה", value: "149" },
{ label: "מעיין ברוך", value: "55" },
{ label: "מעיין צבי", value: "185" },
{ label: "מעיליא", value: "149" },
{ label: "מעין", value: "122" },
{ label: "מעלה אדומים", value: "97" },
{ label: "מעלה אפרים", value: "83" },
{ label: "מעלה גלבוע", value: "154" },
{ label: "מעלה גמלא", value: "59" },
{ label: "מעלה החמישה", value: "98" },
{ label: "מעלה לבונה", value: "88" },
{ label: "מעלה מכמש", value: "93" },
{ label: "מעלה עירון", value: "180" },
{ label: "מעלה עמוס", value: "95" },
{ label: "מעלה שביט", value: "223" },
{ label: "מעלה שומרון", value: "171" },
{ label: "מעלות תרשיחא", value: "149" },
{ label: "מענית", value: "183" },
{ label: "מעסרה", value: "95" },
{ label: "מעש", value: "117" },
{ label: "מפלסים", value: "206" },
{ label: "מפעלי אבשלום", value: "179" },
{ label: "מפעלי ברנר", value: "109" },
{ label: "מפעלי ברקן", value: "168" },
{ label: "מפעלי גלבוע", value: "161" },
{ label: "מפעלי גרנות", value: "183" },
{ label: "מפעלי העמק", value: "126" },
{ label: "מפעלי חבל יבנה", value: "196" },
{ label: "מפעלי ים המלח", value: "246" },
{ label: "מפעלי ים המלח ב' סדום", value: "246" },
{ label: "מפעלי כנות", value: "201" },
{ label: "מפעלי מעון", value: "174" },
{ label: "מפעלי נחם הר טוב", value: "99" },
{ label: "מפעלי צומת מלאכי", value: "234" },
{ label: "מפעלי רותם", value: "125" },
{ label: "מפעלי שאן", value: "154" },
{ label: "מפעלים אזוריים הגליל העליון", value: "55" },
{ label: "מפעלים אזוריים צמח", value: "48" },
{ label: "מצד שמעון", value: "95" },
{ label: "מצדה", value: "123" },
{ label: "מצדות יהודה", value: "122" },
{ label: "מצובה", value: "143" },
{ label: "מצוקי דרגות", value: "84" },
{ label: "מצליח", value: "106" },
{ label: "מצפה", value: "45" },
{ label: "מצפה אבי''ב", value: "75" },
{ label: "מצפה אילן", value: "187" },
{ label: "מצפה יריחו", value: "93" },
{ label: "מצפה נטופה", value: "47" },
{ label: "מצפה רמון", value: "127" },
{ label: "מצפה שלם", value: "84" },
{ label: "מצר", value: "70" },
{ label: "מקווה ישראל", value: "104" },
{ label: "מראח אל בקר", value: "85" },
{ label: "מראח רבאח", value: "95" },
{ label: "מרג' נעג'ה", value: "163" },
{ label: "מרגליות", value: "55" },
{ label: "מרדה", value: "168" },
{ label: "מרום גולן", value: "222" },
{ label: "מרחב עם", value: "127" },
{ label: "מרחביה מושב", value: "161" },
{ label: "מרחביה קיבוץ", value: "161" },
{ label: "מרכז אזורי כדורי", value: "136" },
{ label: "מרכז אזורי מישגב", value: "75" },
{ label: "מרכז אזורי מרום הגליל", value: "52" },
{ label: "מרכז האקדמי רופין", value: "82" },
{ label: "מרכז כ''ח", value: "57" },
{ label: "מרכז מיר''ב", value: "185" },
{ label: "מרכז קהילתי יכון", value: "70" },
{ label: "מרכז קניות ביל''ו", value: "108" },
{ label: "מרכז קניות גן שמואל", value: "183" },
{ label: "מרכז קניות חוצות שפיים", value: "237" },
{ label: "מרכז שוהם", value: "103" },
{ label: "מרכז שפירא", value: "192" },
{ label: "משאבי שדה", value: "223" },
{ label: "משגב דב", value: "113" },
{ label: "משגב עם", value: "55" },
{ label: "משהד", value: "81" },
{ label: "משואה", value: "167" },
{ label: "משואות יצחק", value: "192" },
{ label: "משכיות", value: "163" },
{ label: "משמר איילון", value: "108" },
{ label: "משמר דוד", value: "108" },
{ label: "משמר הירדן", value: "54" },
{ label: "משמר הנגב", value: "179" },
{ label: "משמר העמק", value: "173" },
{ label: "משמר השבעה", value: "238" },
{ label: "משמר השרון", value: "175" },
{ label: "משמרות", value: "189" },
{ label: "משמרת", value: "178" },
{ label: "משען", value: "191" },
{ label: "משרוע בית קאד", value: "158" },
{ label: "מתן", value: "115" },
{ label: "מתקן התפלה פלמחים", value: "258" },
{ label: "מתת", value: "245" },
{ label: "מתתיהו", value: "105" },
{ label: "נאות גולן", value: "46" },
{ label: "נאות הכיכר", value: "215" },
{ label: "נאות חובב", value: "224" },
{ label: "נאות מרדכי", value: "56" },
{ label: "נאות סמדר", value: "215" },
{ label: "נאעורה", value: "161" },
{ label: "נאקורה", value: "165" },
{ label: "נבטים", value: "207" },
{ label: "נבי סאלח", value: "88" },
{ label: "נבי סמואל", value: "91" },
{ label: "נגבה", value: "184" },
{ label: "נגוהות", value: "122" },
{ label: "נג'ידאת", value: "47" },
{ label: "נהורה", value: "184" },
{ label: "נהלל", value: "126" },
{ label: "נהריה", value: "62" },
{ label: "נוב", value: "46" },
{ label: "נובא", value: "100" },
{ label: "נוגה", value: "184" },
{ label: "נווה ", value: "150" },
{ label: "נווה אבות", value: "189" },
{ label: "נווה אור", value: "154" },
{ label: "נווה אטי''ב", value: "44" },
{ label: "נווה אילן", value: "87" },
{ label: "נווה איתן", value: "154" },
{ label: "נווה אפעל", value: "117" },
{ label: "נווה דניאל", value: "85" },
{ label: "נווה הרצוג", value: "196" },
{ label: "נווה זוהר", value: "123" },
{ label: "נווה זיו", value: "151" },
{ label: "נווה חריף", value: "215" },
{ label: "נווה ים", value: "130" },
{ label: "נווה ימין", value: "102" },
{ label: "נווה יער", value: "126" },
{ label: "נווה ירק", value: "115" },
{ label: "נווה מבטח", value: "201" },
{ label: "נווה מיכאל", value: "99" },
{ label: "נווה שלום", value: "99" },
{ label: "נועימה", value: "93" },
{ label: "נועימה מחנה פליטים", value: "93" },
{ label: "נועם", value: "182" },
{ label: "נוף איילון", value: "105" },
{ label: "נופים", value: "171" },
{ label: "נופית", value: "75" },
{ label: "נופך", value: "118" },
{ label: "נוקדים", value: "95" },
{ label: "נור א שמס", value: "158" },
{ label: "נורדיה", value: "175" },
{ label: "נורית", value: "161" },
{ label: "נזלה א שרקיה", value: "156" },
{ label: "נזלה אל ווסטא", value: "158" },
{ label: "נזלה אל ע'רביה", value: "158" },
{ label: "נזלת אבו נאר", value: "158" },
{ label: "נזלת זיד", value: "156" },
{ label: "נזלת עיסא", value: "70" },
{ label: "נחאלין", value: "85" },
{ label: "נחושה", value: "101" },
{ label: "נח''ל אלישע", value: "93" },
{ label: "נחל עוז", value: "214" },
{ label: "נחלה", value: "186" },
{ label: "נחליאל", value: "90" },
{ label: "נחלים", value: "118" },
{ label: "נחם", value: "99" },
{ label: "נחף", value: "66" },
{ label: "נחשולים", value: "185" },
{ label: "נחשון", value: "99" },
{ label: "נחשונים", value: "118" },
{ label: "נטועה", value: "74" },
{ label: "נטור", value: "46" },
{ label: "נטע", value: "204" },
{ label: "נטעים", value: "107" },
{ label: "נטף", value: "87" },
{ label: "ניל''י", value: "90" },
{ label: "נין", value: "161" },
{ label: "ניסף ג'וביל", value: "158" },
{ label: "ניעלין", value: "105" },
{ label: "ניצן", value: "225" },
{ label: "ניצן ב'", value: "225" },
{ label: "ניצנה כפר נוער", value: "210" },
{ label: "ניצני סיני", value: "210" },
{ label: "ניצני עוז", value: "82" },
{ label: "ניצנים", value: "200" },
{ label: "ניר אליהו", value: "178" },
{ label: "ניר בנים", value: "186" },
{ label: "ניר גלים", value: "196" },
{ label: "ניר דוד (תל עמל)", value: "154" },
{ label: "ניר ח''ן", value: "184" },
{ label: "ניר יפה", value: "236" },
{ label: "ניר יצחק", value: "176" },
{ label: "ניר ישראל", value: "191" },
{ label: "ניר משה", value: "229" },
{ label: "ניר עוז", value: "142" },
{ label: "ניר עם", value: "198" },
{ label: "ניר עציון", value: "130" },
{ label: "ניר עקיבא", value: "160" },
{ label: "ניר צבי", value: "239" },
{ label: "נירים", value: "140" },
{ label: "נירית", value: "115" },
{ label: "נירן", value: "83" },
{ label: "נמל חיפה", value: "252" },
{ label: "נמל תעופה בן גוריון", value: "111" },
{ label: "נמרוד", value: "44" },
{ label: "נס הרים", value: "87" },
{ label: "נס עמים", value: "69" },
{ label: "נס ציונה", value: "241" },
{ label: "נעורים", value: "76" },
{ label: "נעלה", value: "90" },
{ label: "נעמי", value: "83" },
{ label: "נען", value: "108" },
{ label: "נצאצרה", value: "124" },
{ label: "נצר חזני", value: "108" },
{ label: "נצר סרני", value: "109" },
{ label: "נצרת", value: "81" },
{ label: "נצרת עילית", value: "81" },
{ label: "נשר", value: "79" },
{ label: "נתיב הגדוד", value: "83" },
{ label: "נתיב הל''ה", value: "99" },
{ label: "נתיב העשרה", value: "155" },
{ label: "נתיב השיירה", value: "69" },
{ label: "נתיבות", value: "157" },
{ label: "נתניה", value: "175" },
{ label: "סאג'ור", value: "66" },
{ label: "סאוויה", value: "88" },
{ label: "סאלם ", value: "165" },
{ label: "סאלם ליד אלון מורה", value: "165" },
{ label: "סאנור", value: "158" },
{ label: "סאסא", value: "245" },
{ label: "סביון", value: "117" },
{ label: "סבסטיה", value: "165" },
{ label: "סגולה", value: "186" },
{ label: "סובא", value: "122" },
{ label: "סוואעד חמרייה", value: "75" },
{ label: "סולם שונם", value: "161" },
{ label: "סוסיה", value: "122" },
{ label: "סופה", value: "176" },
{ label: "סורדה", value: "90" },
{ label: "סוריף", value: "85" },
{ label: "סח'נין", value: "71" },
{ label: "סידא", value: "158" },
{ label: "סילואד", value: "89" },
{ label: "סילת א דהר", value: "158" },
{ label: "סילת אל ח'רית'יה", value: "156" },
{ label: "סימיא", value: "122" },
{ label: "סינג'יל", value: "88" },
{ label: "סיעיר", value: "85" },
{ label: "סיר", value: "158" },
{ label: "סיריס", value: "158" },
{ label: "סלמה", value: "71" },
{ label: "סלעית", value: "165" },
{ label: "סלפית", value: "168" },
{ label: "סמוע", value: "122" },
{ label: "סמר", value: "215" },
{ label: "סניריא", value: "171" },
{ label: "סנסנה", value: "199" },
{ label: "סעד", value: "213" },
{ label: "סער", value: "62" },
{ label: "ספא", value: "90" },
{ label: "ספארין", value: "165" },
{ label: "ספיר", value: "215" },
{ label: "ספסופה", value: "147" },
{ label: "סרה", value: "165" },
{ label: "סרטא", value: "171" },
{ label: "סרכיס", value: "134" },
{ label: "סתריה", value: "108" },
{ label: "עאבה", value: "158" },
{ label: "עאבוד", value: "88" },
{ label: "עאטוף", value: "163" },
{ label: "עאנין", value: "156" },
{ label: "עבדאללה איברהים", value: "95" },
{ label: "עבדה", value: "122" },
{ label: "עבדון", value: "151" },
{ label: "עבווין", value: "88" },
{ label: "עברון", value: "62" },
{ label: "ע'גה", value: "158" },
{ label: "עג'ול", value: "88" },
{ label: "עגור", value: "101" },
{ label: "ע'ג'ר", value: "50" },
{ label: "עד הלום", value: "196" },
{ label: "עדי", value: "75" },
{ label: "עדנים", value: "115" },
{ label: "עובידייה", value: "95" },
{ label: "עוג'א אתחתא", value: "83" },
{ label: "עווד", value: "122" },
{ label: "עוורתא", value: "165" },
{ label: "עוזה", value: "235" },
{ label: "עוזיז", value: "122" },
{ label: "עוזייר", value: "72" },
{ label: "עולש", value: "82" },
{ label: "עומר", value: "242" },
{ label: "עוסארין", value: "165" },
{ label: "עופר", value: "185" },
{ label: "עופרים", value: "92" },
{ label: "עוצם", value: "184" },
{ label: "עוקבי", value: "199" },
{ label: "עוריף", value: "165" },
{ label: "עזאזמה", value: "205" },
{ label: "עזאזמה דרומית לרמת חובב", value: "205" },
{ label: "עזאזמה דרומית לשגב שלום", value: "205" },
{ label: "עזאזמה מזרחית לרמת חובב", value: "205" },
{ label: "עזוז", value: "223" },
{ label: "עזון", value: "171" },
{ label: "עזון עתמה", value: "171" },
{ label: "עזמוט", value: "165" },
{ label: "עזר", value: "193" },
{ label: "עזריאל", value: "178" },
{ label: "עזריה", value: "108" },
{ label: "עזריקם", value: "193" },
{ label: "עטארה", value: "158" },
{ label: "עטארה ליד ביר זית ", value: "88" },
{ label: "עטרת", value: "88" },
{ label: "עידן", value: "215" },
{ label: "עיזרייה", value: "97" },
{ label: "עיילבון", value: "47" },
{ label: "עיינות", value: "241" },
{ label: "עילאר", value: "158" },
{ label: "עילוט", value: "126" },
{ label: "עילת עלי", value: "95" },
{ label: "עין א סולטאן ", value: "93" },
{ label: "עין איוב", value: "90" },
{ label: "עין איילה", value: "185" },
{ label: "עין אל אסד", value: "66" },
{ label: "עין אל בידא", value: "158" },
{ label: "עין אל מטווי", value: "168" },
{ label: "עין בוקק", value: "123" },
{ label: "עין גב", value: "48" },
{ label: "עין גדי", value: "123" },
{ label: "עין דור", value: "136" },
{ label: "עין הבשור", value: "174" },
{ label: "עין הוד", value: "130" },
{ label: "עין החורש", value: "78" },
{ label: "עין המפרץ", value: "69" },
{ label: "עין הנצי''ב", value: "154" },
{ label: "עין העמק", value: "173" },
{ label: "עין השופט", value: "173" },
{ label: "עין השלושה", value: "140" },
{ label: "עין ורד", value: "178" },
{ label: "עין זיוון", value: "222" },
{ label: "עין חוד/אבו אל היג'אל", value: "130" },
{ label: "עין חצבה", value: "215" },
{ label: "עין חרוד איחוד", value: "161" },
{ label: "עין חרוד מאוחד", value: "161" },
{ label: "עין יאנון", value: "165" },
{ label: "עין יברוד", value: "90" },
{ label: "עין יהב", value: "215" },
{ label: "עין יעקב", value: "151" },
{ label: "עין כמונים", value: "52" },
{ label: "עין כרם בי''ס חקלאי", value: "98" },
{ label: "עין כרמל", value: "130" },
{ label: "עין מאהל", value: "81" },
{ label: "עין נקובא", value: "87" },
{ label: "עין סיניא", value: "90" },
{ label: "עין עירון", value: "189" },
{ label: "עין עריכ", value: "90" },
{ label: "עין צורים", value: "192" },
{ label: "עין קיניא", value: "90" },
{ label: "עין קנייא", value: "44" },
{ label: "עין ראפה", value: "87" },
{ label: "עין שמר", value: "189" },
{ label: "עין שריד", value: "178" },
{ label: "עין תמר", value: "215" },
{ label: "עינאבוס", value: "165" },
{ label: "עינבר", value: "47" },
{ label: "עינת", value: "240" },
{ label: "עיספיא", value: "129" },
{ label: "עיר אובות", value: "215" },
{ label: "עיר כרמל", value: "129" },
{ label: "עיראק בורין", value: "165" },
{ label: "עכו", value: "69" },
{ label: "עלומים", value: "214" },
{ label: "עלי", value: "89" },
{ label: "עלי זהב", value: "92" },
{ label: "עלמה", value: "61" },
{ label: "עלמון/ראפה", value: "93" },
{ label: "עמוקה", value: "54" },
{ label: "עמוריה", value: "88" },
{ label: "עמינדב", value: "86" },
{ label: "עמיעד", value: "60" },
{ label: "עמיעוז", value: "146" },
{ label: "עמיקם", value: "181" },
{ label: "עמיר", value: "56" },
{ label: "עמנואל", value: "171" },
{ label: "עמקה", value: "68" },
{ label: "ענאב אל כביר", value: "122" },
{ label: "ענאתא", value: "96" },
{ label: "ענב", value: "165" },
{ label: "ענזה", value: "158" },
{ label: "ענתבא", value: "158" },
{ label: "עסירה א שמאליה", value: "158" },
{ label: "עסירה אל קיבליה", value: "165" },
{ label: "עסכר", value: "165" },
{ label: "עפולה", value: "161" },
{ label: "עפרה", value: "89" },
{ label: "עץ אפרים", value: "171" },
{ label: "עקאבת גיבר", value: "93" },
{ label: "עקבה בשומרון", value: "158" },
{ label: "עקבת תיאסיר", value: "158" },
{ label: "עקרבה", value: "165" },
{ label: "עראבה", value: "71" },
{ label: "עראבה ליד ג'נין", value: "156" },
{ label: "עראמשה", value: "141" },
{ label: "עראנה", value: "158" },
{ label: "ערב א שמע", value: "95" },
{ label: "ערב אזונר", value: "71" },
{ label: "ערב אל גנאדי", value: "75" },
{ label: "ערב אל נעים", value: "75" },
{ label: "ערב אל סגיראת", value: "75" },
{ label: "ערב אל סמניה", value: "75" },
{ label: "ערב אל עיסאת", value: "126" },
{ label: "ערב אל פמאז", value: "81" },
{ label: "ערבונה", value: "158" },
{ label: "ערד", value: "124" },
{ label: "ערוגות", value: "234" },
{ label: "ערורה", value: "88" },
{ label: "ערערה", value: "187" },
{ label: "ערערה בנגב", value: "124" },
{ label: "ערקה", value: "156" },
{ label: "עשרת", value: "113" },
{ label: "עתיל", value: "158" },
{ label: "עתלית", value: "130" },
{ label: "עתניאל", value: "122" },
{ label: "פארן", value: "215" },
{ label: "פארעה אל ג'פתלכ", value: "163" },
{ label: "פארק מדע ותעשייה מבוא כרמל", value: "173" },
{ label: "פארק תעשיות ספירים", value: "198" },
{ label: "פארק תעשיות עמק חפר", value: "76" },
{ label: "פארק תעשיות פלמחים", value: "107" },
{ label: "פארק תעשיות קדמת גליל", value: "49" },
{ label: "פארק תעשיות רמת דלתון", value: "61" },
{ label: "פדואל", value: "92" },
{ label: "פדויים", value: "43" },
{ label: "פדיה", value: "108" },
{ label: "פוקיקיס", value: "122" },
{ label: "פוריה כפר עבודה", value: "49" },
{ label: "פוריה נווה עובד", value: "49" },
{ label: "פוריה עילית", value: "49" },
{ label: "פורת", value: "178" },
{ label: "פחמה", value: "158" },
{ label: "פטיש", value: "195" },
{ label: "פיראסין", value: "156" },
{ label: "פלאמה", value: "165" },
{ label: "פלך", value: "67" },
{ label: "פלמחים", value: "106" },
{ label: "פנדקומיה", value: "158" },
{ label: "פני חבר", value: "122" },
{ label: "פסאיל ", value: "83" },
{ label: "פסגות", value: "91" },
{ label: "פסוטה", value: "74" },
{ label: "פעמי תש''ז", value: "160" },
{ label: "פצאל", value: "83" },
{ label: "פקועה", value: "158" },
{ label: "פקיעין חדשה", value: "145" },
{ label: "פקיעין/בוקיעה", value: "145" },
{ label: "פרדס חנה כרכור", value: "189" },
{ label: "פרדסיה", value: "178" },
{ label: "פרוד", value: "52" },
{ label: "פרוש בית דג'ן", value: "163" },
{ label: "פרזון", value: "236" },
{ label: "פרח'ה", value: "168" },
{ label: "פרי גן", value: "148" },
{ label: "פרידיס", value: "185" },
{ label: "פרעון", value: "165" },
{ label: "פרעתה", value: "165" },
{ label: "פתח תקווה", value: "119" },
{ label: "פתחיה", value: "108" },
{ label: "צאלים", value: "194" },
{ label: "צביה", value: "71" },
{ label: "צבעון", value: "145" },
{ label: "צובה", value: "98" },
{ label: "צוחר", value: "144" },
{ label: "צופיה", value: "113" },
{ label: "צופין", value: "171" },
{ label: "צופית", value: "102" },
{ label: "צופר", value: "215" },
{ label: "צוקי ים", value: "175" },
{ label: "צוקים", value: "215" },
{ label: "צור הדסה", value: "86" },
{ label: "צור יגאל", value: "178" },
{ label: "צור יצחק", value: "178" },
{ label: "צור משה", value: "178" },
{ label: "צור נתן", value: "178" },
{ label: "צוריאל", value: "145" },
{ label: "צורית", value: "66" },
{ label: "ציפורי", value: "81" },
{ label: "צלפון", value: "99" },
{ label: "צנדלה", value: "236" },
{ label: "צפריה", value: "238" },
{ label: "צפרירים", value: "101" },
{ label: "צפת", value: "51" },
{ label: "צרופה", value: "185" },
{ label: "צריפין", value: "106" },
{ label: "צרעה", value: "99" },
{ label: "קבאטיה", value: "158" },
{ label: "קבועה", value: "124" },
{ label: "קבוצת יבנה", value: "113" },
{ label: "קבלאן", value: "89" },
{ label: "קדומים", value: "165" },
{ label: "קדימה צורן", value: "178" },
{ label: "קדיתא", value: "52" },
{ label: "קדמה", value: "186" },
{ label: "קדמת צבי", value: "59" },
{ label: "קדר", value: "97" },
{ label: "קדרון", value: "112" },
{ label: "קדרים", value: "47" },
{ label: "קובסי", value: "66" },
{ label: "קודייראת א צאנה", value: "124" },
{ label: "קוואעין", value: "122" },
{ label: "קוזה", value: "165" },
{ label: "קוממיות", value: "186" },
{ label: "קוסין", value: "165" },
{ label: "קוסרה", value: "89" },
{ label: "קורנית", value: "75" },
{ label: "קטורה", value: "215" },
{ label: "קיביא", value: "90" },
{ label: "קילקיס", value: "122" },
{ label: "קיסריה", value: "190" },
{ label: "קירה", value: "168" },
{ label: "קלחים", value: "160" },
{ label: "קליה", value: "93" },
{ label: "קלנדיה", value: "90" },
{ label: "קלנסווה", value: "178" },
{ label: "קלקיליה", value: "171" },
{ label: "קסר א סיר", value: "125" },
{ label: "קפין", value: "156" },
{ label: "קציעות", value: "223" },
{ label: "קציר חריש", value: "187" },
{ label: "קצרין", value: "59" },
{ label: "קראות בני זיד", value: "88" },
{ label: "קראות בני חסן", value: "171" },
{ label: "קריות", value: "89" },
{ label: "קרית אונו", value: "117" },
{ label: "קרית ארבע", value: "122" },
{ label: "קרית אתא", value: "134" },
{ label: "קרית ביאליק", value: "220" },
{ label: "קרית גת", value: "182" },
{ label: "קרית חיים", value: "220" },
{ label: "קרית חינוך מרחבים", value: "43" },
{ label: "קרית חינוך שדות נגב", value: "157" },
{ label: "קרית טבעון", value: "128" },
{ label: "קרית ים", value: "220" },
{ label: "קרית יערים מוסד", value: "87" },
{ label: "קרית יערים/טלז סטון", value: "87" },
{ label: "קרית מוצקין", value: "220" },
{ label: "קרית מלאכי", value: "234" },
{ label: "קרית נטפים", value: "168" },
{ label: "קרית ענבים", value: "98" },
{ label: "קרית עקרון", value: "108" },
{ label: "קרית שלמה", value: "237" },
{ label: "קרית שמואל", value: "220" },
{ label: "קרית שמונה", value: "55" },
{ label: "קרית תעופה", value: "103" },
{ label: "קרנב אבו סלב", value: "125" },
{ label: "קרני שומרון", value: "171" },
{ label: "קשכר נבארי", value: "124" },
{ label: "קשת", value: "222" },
{ label: "ראבא", value: "158" },
{ label: "ראבוד", value: "122" },
{ label: "ראם תשלובת חקלאית", value: "223" },
{ label: "ראמה", value: "66" },
{ label: "ראמין", value: "165" },
{ label: "ראס אל עין", value: "71" },
{ label: "ראס כרכר", value: "90" },
{ label: "ראס סניסיל", value: "95" },
{ label: "ראס עלי", value: "75" },
{ label: "ראפאת", value: "92" },
{ label: "ראפאת ליד סמוע", value: "122" },
{ label: "ראש העין", value: "118" },
{ label: "ראש פינה", value: "60" },
{ label: "ראש צורים", value: "85" },
{ label: "ראשון לציון", value: "107" },
{ label: "רבבה", value: "168" },
{ label: "רבדים", value: "112" },
{ label: "רביבים", value: "223" },
{ label: "רביד", value: "53" },
{ label: "רגבה", value: "62" },
{ label: "רגבים", value: "181" },
{ label: "רהט", value: "179" },
{ label: "רוג'ייב", value: "165" },
{ label: "רוגלית", value: "99" },
{ label: "רוג'ם אום ח'יר", value: "122" },
{ label: "רווחה", value: "186" },
{ label: "רוויה", value: "154" },
{ label: "רוח במדבר", value: "223" },
{ label: "רוחמה", value: "162" },
{ label: "רומאנה", value: "72" },
{ label: "רומאנה ממזרח לאום אל פחם", value: "156" },
{ label: "רומיחאת", value: "134" },
{ label: "רומת היב", value: "72" },
{ label: "רועי", value: "163" },
{ label: "רוקעה", value: "122" },
{ label: "רותם", value: "163" },
{ label: "רחוב", value: "154" },
{ label: "רחובות", value: "109" },
{ label: "רחלים", value: "89" },
{ label: "רח'מה", value: "125" },
{ label: "ריחאנייה", value: "61" },
{ label: "ריחן", value: "187" },
{ label: "ריינה", value: "81" },
{ label: "רימונים", value: "93" },
{ label: "רינתיה", value: "118" },
{ label: "רכסים", value: "134" },
{ label: "רם און", value: "236" },
{ label: "רמאללה", value: "90" },
{ label: "רמה", value: "158" },
{ label: "רמות", value: "48" },
{ label: "רמות השבים", value: "115" },
{ label: "רמות מאיר", value: "108" },
{ label: "רמות מנשה", value: "173" },
{ label: "רמות נפתלי", value: "57" },
{ label: "רמלה", value: "106" },
{ label: "רמת אפעל", value: "117" },
{ label: "רמת גן", value: "120" },
{ label: "רמת דוד", value: "126" },
{ label: "רמת הכובש", value: "178" },
{ label: "רמת השופט", value: "173" },
{ label: "רמת השרון", value: "116" },
{ label: "רמת יוחנן", value: "134" },
{ label: "רמת ישי", value: "126" },
{ label: "רמת מגשימים", value: "46" },
{ label: "רמת צבי", value: "236" },
{ label: "רמת רזיאל", value: "87" },
{ label: "רמת רחל", value: "96" },
{ label: "רנן", value: "231" },
{ label: "רעים", value: "137" },
{ label: "רעננה", value: "114" },
{ label: "רפידא", value: "95" },
{ label: "רפידיה", value: "165" },
{ label: "רקפת", value: "75" },
{ label: "רשפון", value: "114" },
{ label: "רשפים", value: "154" },
{ label: "רתמים", value: "223" },
{ label: "שאר ישוב", value: "50" },
{ label: "שבות רחל", value: "89" },
{ label: "שבי דרום", value: "160" },
{ label: "שבי ציון", value: "244" },
{ label: "שבי שומרון", value: "165" },
{ label: "שבלי", value: "136" },
{ label: "שבתין", value: "90" },
{ label: "שגב שלום", value: "207" },
{ label: "שגב/עצמון", value: "75" },
{ label: "שגור", value: "66" },
{ label: "שדה אילן", value: "49" },
{ label: "שדה אליהו", value: "154" },
{ label: "שדה אליעזר", value: "54" },
{ label: "שדה בוקר", value: "127" },
{ label: "שדה דוד", value: "227" },
{ label: "שדה ורבורג", value: "178" },
{ label: "שדה יואב", value: "184" },
{ label: "שדה יעקב", value: "126" },
{ label: "שדה יצחק", value: "183" },
{ label: "שדה משה", value: "182" },
{ label: "שדה נחום", value: "154" },
{ label: "שדה נחמיה", value: "56" },
{ label: "שדה ניצן", value: "144" },
{ label: "שדה עוזיהו", value: "193" },
{ label: "שדה צבי", value: "160" },
{ label: "שדות ים", value: "190" },
{ label: "שדות מיכה", value: "101" },
{ label: "שדי אברהם", value: "148" },
{ label: "שדי חמד", value: "115" },
{ label: "שדי תרומות", value: "154" },
{ label: "שדמה", value: "113" },
{ label: "שדמות דבורה", value: "136" },
{ label: "שדמות מחולה", value: "163" },
{ label: "שדרות", value: "198" },
{ label: "שואבה", value: "87" },
{ label: "שובה", value: "133" },
{ label: "שובל", value: "179" },
{ label: "שוהם", value: "103" },
{ label: "שוויכה", value: "158" },
{ label: "שוויכה בהר חברון", value: "122" },
{ label: "שומרה", value: "132" },
{ label: "שומריה", value: "204" },
{ label: "שופה", value: "165" },
{ label: "שוקבא", value: "90" },
{ label: "שוקדה", value: "133" },
{ label: "שורש", value: "87" },
{ label: "שורשים", value: "75" },
{ label: "שושנת העמקים", value: "175" },
{ label: "שזור", value: "66" },
{ label: "שחר", value: "184" },
{ label: "שחרות", value: "215" },
{ label: "שיבולים", value: "159" },
{ label: "שיבטה", value: "223" },
{ label: "שיטים", value: "243" },
{ label: "שייח' אחמד אל עבד", value: "122" },
{ label: "שייח' דנון", value: "69" },
{ label: "שילה", value: "89" },
{ label: "שילת", value: "105" },
{ label: "שכם", value: "165" },
{ label: "שכניה", value: "75" },
{ label: "שלווה", value: "235" },
{ label: "שלוחות", value: "154" },
{ label: "שלומי", value: "143" },
{ label: "שלומית", value: "150" },
{ label: "שלומציון", value: "167" },
{ label: "שמיר", value: "56" },
{ label: "שמעה", value: "122" },
{ label: "שמרה", value: "69" },
{ label: "שמשית", value: "126" },
{ label: "שני ליבנה", value: "122" },
{ label: "שניר", value: "50" },
{ label: "שעב", value: "75" },
{ label: "שעורים", value: "136" },
{ label: "שעל", value: "59" },
{ label: "שעלבים", value: "105" },
{ label: "שער אפרים", value: "178" },
{ label: "שער הגולן", value: "48" },
{ label: "שער העמקים", value: "128" },
{ label: "שער מנשה", value: "183" },
{ label: "שערי תקווה", value: "171" },
{ label: "שפיים", value: "237" },
{ label: "שפיר", value: "192" },
{ label: "שפר", value: "52" },
{ label: "שפרעם", value: "75" },
{ label: "שקבא", value: "92" },
{ label: "שקד", value: "156" },
{ label: "שקף", value: "204" },
{ label: "שרונה", value: "49" },
{ label: "שריגים", value: "101" },
{ label: "שריד", value: "126" },
{ label: "שרשרת", value: "159" },
{ label: "שתולה", value: "132" },
{ label: "שתולים", value: "193" },
{ label: "תארבין א צאנה שבט", value: "205" },
{ label: "תאשור", value: "159" },
{ label: "תדהר", value: "159" },
{ label: "תובל", value: "67" },
{ label: "תומר", value: "83" },
{ label: "תוקוע", value: "95" },
{ label: "תורמוס עייא", value: "89" },
{ label: "תושיה", value: "133" },
{ label: "תחנת הכוח אלון תבור", value: "256" },
{ label: "תחנת הכוח אשדוד", value: "248" },
{ label: "תחנת הכוח גזר", value: "257" },
{ label: "תחנת הכוח חגית", value: "254" },
{ label: "תחנת הכוח חיפה", value: "251" },
{ label: "תחנת הכוח צפית", value: "247" },
{ label: "תחנת הכוח רוטנברג", value: "249" },
{ label: "תחנת הכוח רידינג", value: "250" },
{ label: "תחנת הכוח רמת חובב", value: "255" },
{ label: "תחנת ניסיונות גילת", value: "203" },
{ label: "תיאסיר", value: "158" },
{ label: "תימורים", value: "234" },
{ label: "תיעניכ", value: "156" },
{ label: "תירוש", value: "101" },
{ label: "תל", value: "165" },
{ label: "תל א בידה", value: "163" },
{ label: "תל א שמסיה", value: "163" },
{ label: "תל אביב יפו", value: "121" },
{ label: "תל חי", value: "55" },
{ label: "תל יוסף", value: "236" },
{ label: "תל יצחק", value: "237" },
{ label: "תל מונד", value: "178" },
{ label: "תל עדשים", value: "81" },
{ label: "תל קציר", value: "48" },
{ label: "תל שבע", value: "242" },
{ label: "תל תאומים", value: "154" },
{ label: "תלם", value: "100" },
{ label: "תלמי אליהו", value: "144" },
{ label: "תלמי אלעזר", value: "183" },
{ label: "תלמי ביל''ו", value: "160" },
{ label: "תלמי יוסף", value: "148" },
{ label: "תלמי יחיאל", value: "197" },
{ label: "תלמי יפה", value: "226" },
{ label: "תלמים", value: "227" },
{ label: "תלפית", value: "158" },
{ label: "תלפית  במרכז השומרון", value: "89" },
{ label: "תמרת", value: "126" },
{ label: "תנובות", value: "82" },
{ label: "תנין", value: "158" },
{ label: "תעוז", value: "99" },
{ label: "תעמרה", value: "95" },
{ label: "תעשיון השרון", value: "119" },
{ label: "תעשיון חצב", value: "118" },
{ label: "תעשיון מבצע", value: "201" },
{ label: "תעשיון צריפין", value: "239" },
{ label: "תעשיון ראם", value: "197" },
{ label: "תעשיון שח''ק", value: "156" },
{ label: "תעשיון תמ''ד", value: "125" },
{ label: "תעשיות שער הנגב", value: "198" },
{ label: "תעשייון בר לב", value: "75" },
{ label: "תפוח", value: "122" },
{ label: "תפרח", value: "203" },
{ label: "תקומה", value: "260" },
{ label: "תקוע", value: "95" },
{ label: "תראבין א צאנה", value: "179" },
{ label: "תראמה", value: "122" },
{ label: "תרדיון", value: "71" },
{ label: "תרום", value: "99" },
{ label: "תרקומיא", value: "100" }];
document.addEventListener('DOMContentLoaded', function() {
  
    var dataList = document.getElementById('json-datalist');
    cities.forEach(function (item) {
        // Create a new <option> element.
        var option = document.createElement('option');
        // Set the value using the item in the JSON array.
        option.value = item.label;
        option.id = item.value;
        // Add the <option> element to the <datalist>.
        dataList.appendChild(option);
    });
    // Initialize the option controls.
    options.isActivated.checked = localStorage.isActivated || true;
    // The display activation.
    options.frequency.value = localStorage.frequency || null;
    // The display frequency, in minutes.

    if (!options.isActivated.checked) { ghost(true); }

    // Set the display activation and frequency.


    options.but.onclick = function () {
        localStorage.isActivated = options.isActivated.checked;
        localStorage.SoundActivated = options.SoundActivated.checked;
        localStorage.mycity = getID(options.frequency.value);
        localStorage.frequency = options.frequency.value;
    };
});
function getID(value) {


    for (var i = 0; i < cities.length; i++) {
        if (cities[i]["label"] === value) {
            return (cities[i]["value"]);
        }
    }
}
